config/routes.rb
    resources :entries, only: [:index], module: :employees
    resources :cash_counts, only: [:new, :create], module: :employees
    resources :bill_counts, only: [:create], module: :employees
    resources :cash_on_hand_accounts, only: [:show], module: :employees do
    end
  end
  resources :cash_accounts, only: [:show] do

    resources :expenses, only: [:new, :create], module: :cash_accounts
    resources :cash_transfers, only: [:new, :create], module: :cash_accounts

  end
  resources :work_orders, only: [:index, :new, :create] do
    resources :payments, only: [:ew, :create], module: :work_orders
  end
  resources :work_order_statuses, only: [:edit, :update]
  namespace :computer_repair_section do
    resources :dashboard, only: [:index]
    resources :insights, only: [:index]


    resources :work_orders do
      resources :endorsements,    only: [:edit, :update], module: :work_orders
      resources :service_charges, only: [:new, :create, :destroy], module: :work_orders
      resources :additional_charges, only: [:new, :create], module: :work_orders
      resources :spare_parts, only: [:new, :create, :destroy]
      resources :service_claim_tags, only: [:show]
      resources :payments, module: :work_orders, only: [:new, :create]
      resources :refunds, module: :work_orders, only: [:new, :create]
      resources :charge_invoices, only: [:new, :create], module: :work_orders
    end
    resources :work_order_updates, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :knowledge_center, only: [:index]
  resources :product_units, shallow: true do
    resources :accessories, only: [:new, :create]
  end

  resources :sections, only: [:new, :create]
  resources :other_sales, only: [:new, :create]
  resources :entries, only: [:destroy]
  resources :capital_withdrawals, only: [:new, :create]
  resources :accessories, only: [:destroy]
  resources :search_results, only: [:index]
  resources :customer_account_mergings, only: [:new, :create], module: :settings
  resources :charge_invoices, only: [:index, :edit, :update]
  resources :cash_on_hand_accounts, only: [:new, :create], module: :accounting

  namespace :store_front_module do
    resources :stocks, only: [:show] do
      resources :sales, only: [:index], module: :stocks
      resources :internal_uses, only: [:index], module: :stocks
      resources :stock_transfers, only: [:index], module: :stocks
    end
    resources :sales_order_line_items, only: [:show, :edit, :update] do
      resources :cancellations, only: [:create], module: :sales_order_line_items
      resources :sales_returns, only: [:new, :create], module: :sales_order_line_items

    end
    resources :stock_transfer_order_line_items, only: [:show] do
      resources :cancellations, only: [:create], module: :stock_transfer_order_line_items
    end
    resources :purchase_order_line_items, only: [:show]

    resources :store_fronts, only: [:index, :show] do
      resources :sales_orders, only: [:index],               module: :store_fronts
      resources :accounts,    only: [:index, :new, :create], module: :store_fronts
      resources :reports,     only: [:index],                module: :store_fronts
      resources :inventories, only: [:index],                module: :store_fronts
      resources :work_orders, only: [:index],                module: :store_fronts
    end
    resources :stock_registry_processings, only: [:create]
    resources :stock_transfer_registries, only: [:new, :create, :show], module: :registries
    resources :received_stock_transfer_registries, only: [:new, :create, :show], module: :registries
    resources :purchase_order_registries, only: [:new, :create, :show, :destroy], module: :registries do
      resources :purchase_order_line_items, only: [:destroy]
    end
    resources :customers, only: [:show] do
      resources :credit_sales_order_line_item_processings, only: [:new, :create, :destroy]
      resources :cash_sales_order_line_item_processings, only: [:new, :create, :destroy]

      resources :credit_sales_order_processings, only: [:create], module: :order_processings
    end
    resources :credit_sales_orders, only: [:show] do
      resources :payments, only: [:new, :create], module: :credit_sales_orders
    end
    resources :line_items, only: [:show]
    resources :spoilages, only: [:index, :show], module: :orders
    resources :spoilage_order_line_item_processings, only: [:new, :create, :destroy], module: :line_items
    resources :spoilage_order_processings, only: [:create], module: :orders
    resources :purchase_order_line_item_registries, only: [:create]
    resources :unit_of_measurements, only: [:edit, :update], module: :settings
    resources :selling_prices, only: [:new, :create], module: :settings
    resources :stock_transfers, only: [:index, :show, :edit, :update, :destroy], module: :orders do
      resources :additional_line_items,                  only: [:new, :create, :destroy], module: :stock_transfer_orders
      resources :additional_line_item_order_processings, only: [:create], module: :stock_transfer_orders
    end
    resources :received_stock_transfers, only: [:index, :show], module: :orders
    resources :repair_services_orders, only: [:index, :show], module: :orders
    resources :sales_returns, only: [:index, :show], module: :orders
    resources :stock_transfer_order_line_item_processings, only: [:new, :create, :destroy], module: :line_items
    resources :received_stock_transfer_order_line_item_processings, only: [:new, :create, :destroy], module: :line_items
    resources :sales_return_order_line_item_processings, only: [:new, :create, :destroy], module: :line_items
    resources :product_mergings, only: [:new, :create], module: :settings
    resources :purchase_orders, only: [:new, :index, :show], module: :orders do
      resources :cancellations, only: [:create], module: :purchase_orders
    end
    resources :internal_use_orders, only: [:index, :show], module: :orders
    resources :purchase_returns, only: [:index, :show], module: :orders
    resources :sales_orders, only: [:index, :show, :destroy], module: :orders do
      resources :additional_line_items, only: [:new, :create, :destroy], module: :sales_orders
      resources :additional_line_item_processings, only: [:create], module: :sales_orders
      resources :additional_other_sales_items, only: [:new, :create, :destroy], module: :sales_orders
      resources :other_sales_line_item_cancellations, only: [:destroy], module: :sales_orders
      resources :additional_other_sales_item_order_processings, only: [:new, :create], module: :sales_orders
    end
    resources :purchase_order_line_item_processings, only: [:new, :create, :destroy], module: :line_items
    resources :purchase_return_order_line_item_processings, only: [:new, :create, :destroy], module: :line_items
    resources :sales_order_line_item_processings, only: [:new, :create, :destroy], module: :line_items
    resources :internal_use_order_line_item_processings, only: [:new, :create, :destroy], module: :line_items
    resources :purchase_order_processings, only: [:create], module: :orders
    resources :purchase_return_order_processings, only: [:create], module: :orders
    resources :sales_order_processings, only: [:create], module: :orders
    resources :stock_transfer_order_processings, only: [:create], module: :orders
    resources :received_stock_transfer_order_processings, only: [:create], module: :orders
    resources :sales_return_order_processings, only: [:create], module: :orders
    resources :internal_use_order_processings, only: [:create], module: :orders
  end

  resources :voucher_amounts, only: [:destroy]
  resources :vouchers, only: [:index, :show] do
    resources :disbursements, only: [:new, :create], module: :vouchers
    resources :confirmations, only: [:create], module: :vouchers
  end
  namespace :repair_services_module do
      resources :repair_service_order_line_item_processings, only: [:destroy]
    resources :work_orders, only: [:show] do
      resources :service_charge_processings, only: [:new, :create]
      resources :payment_processings, only: [:new, :create, :show]
      resources :repair_service_order_line_item_processings, only: [:new, :create, :destroy]
      resources :spare_part_cancellations, only: [:destroy]

      resources :repair_service_order_processings, only: [:new, :create]
    end
    resources :service_payments, only: [:index, :show]
  end
  namespace :settings do
    resources :store_fronts, only: [:new, :create, :edit, :update]
  end

  resources :income_statement, only: [:index]
  namespace :accounting do
    resources :accounts, only: [:new, :create]
    resources :adjusting_entries, only: [:create]
    resources :entry_line_items, only: [:new, :create]
    resources :employees, only: [:show] do
      resources :cash_transfers, only: [:new, :create]
    end
    resources :bank_accounts, only: [:new, :create, :show] do
      resources :deposits, only: [:new, :create], module: :bank_accounts
      resources :withdrawals, only: [:new, :create], module: :bank_accounts
    end
    resources :finances, only: [:index]
    resources :entries, only: [:index, :show]
    resources :accounts, only: [:index, :show, :new, :create, :edit, :update] do
    match "/deactivate" => "accounts#deactivate",  via: [:post], on: :member

    end
  end
  resources :inventories, only: [:index, :show]
  resources :dashboard, only: [:index]
  namespace :admin do
    resources :employees, only: [:show] do
      resources :reports,  only: [:index], module: :employees
      resources :sales,    only: [:index], module: :employees
      resources :entries,  only: [:index], module: :employees
      resources :settings, only: [:index], module: :employees
      resources :cash_accounts, only: [:new, :create], module: :employees
    end
  end
  resources :credit_payments, only: [:index, :show]
  resources :employees, only: [:index, :show]
  namespace :repair_services do

app/models/registry.rb
require 'roo'
class Registry < ApplicationRecord
  belongs_to :employee, class_name: "User"
	has_attached_file :spreadsheet, :path => ":rails_root/public/system/:attachment/:id/:filename"
  do_not_validate_attachment_file_type :spreadsheet
  has_many :line_items, dependent: :destroy

end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController
	def create
		@registry = Registry.create(registry_params)
		if @registry.save 
			redirect_to @registry, notice: 'Stocks imported successfully.'
		else 
			redirect_to stocks_url, alert: 'Invalid file.'
		end
	end 
  def show 
    @registry = Registry.find(params[:id])
    @stocks = @registry.stocks.all.paginate(page: params[:page], per_page: 35)
  end
  def destroy
    @registry = Registry.find(params[:id])
    @registry.destroy 
    redirect_to products_url, notice: "Deleted successfully."
  end

	private 
	def registry_params
		params.require(:registry).permit(:spreadsheet)
	end
end 

app/controllers/store_front_module/registries/purchase_order_line_items_controller.rb
module StoreFrontModule
  module Registries
    class PurchaseOrderLineItemsController < ApplicationController
      def destroy
        @registry = StoreFrontModule::Registries::PurchaseOrderRegistry.find(params[:purchase_order_registry_id])
        @line_item = @registry.purchase_order_line_items.find(params[:id])
        @line_item.destroy
        redirect_to store_front_module_purchase_order_registry_url(@registry), notice: "Removed successfully."
      end
    end
  end
end

app/controllers/store_front_module/registries/purchase_order_registries_controller.rb
module StoreFrontModule
  module Registries
    class PurchaseOrderRegistriesController < ApplicationController
      def new
        @registry = StoreFrontModule::Registries::PurchaseOrderRegistry.new
      end
      def create
        @registry = StoreFrontModule::Registries::PurchaseOrderRegistry.create(registry_params)
        if @registry.valid?
          @registry.save
          @registry.parse_for_records
          redirect_to store_front_module_purchase_order_registry_url(@registry), notice: "Uploaded successfully"
        else
          render :new
        end
      end

      def show
        @registry = StoreFrontModule::Registries::PurchaseOrderRegistry.find(params[:id])
        @purchase_order_line_items = @registry.purchase_order_line_items.order(created_at: :asc).paginate(page: params[:page], per_page: 35)
        @cart = current_cart
        @purchase_order = StoreFrontModule::Orders::PurchaseOrderProcessing.new
      end
      def destroy
        @registry = StoreFrontModule::Registries::PurchaseOrderRegistry.find(params[:id])
        @registry.destroy
        redirect_to store_front_module_purchase_orders_url, notice: "Purchases cancelled successfully."
      end

      private
      def registry_params
        params.require(:store_front_module_registries_purchase_order_registry).permit(:spreadsheet, :employee_id)
      end
    end
  end
end

app/controllers/store_front_module/registries/received_stock_transfer_registries_controller.rb
 module StoreFrontModule
  module Registries
    class ReceivedStockTransferRegistriesController < ApplicationController
      def new
        @registry = StoreFrontModule::Registries::ReceivedStockTransferRegistry.new
      end
      def create
        @registry = StoreFrontModule::Registries::ReceivedStockTransferRegistry.new(registry_params)
        if @registry.save
          @registry.parse_for_records
          redirect_to store_front_module_received_stock_transfer_registry_url(@registry), notice: "uploaded successfully"
        else
          render :new
        end
      end
      def show
        @registry = StoreFrontModule::Registries::ReceivedStockTransferRegistry.find(params[:id])
        @cart = current_cart
        @received_stock_transfer_order = StoreFrontModule::Orders::ReceivedStockTransferOrderProcessing.new
      end
      private
      def registry_params
        params.require(:store_front_module_registries_received_stock_transfer_registry).
        permit(:spreadsheet)
      end
    end
  end
end

app/controllers/store_front_module/registries/stock_transfer_registries_controller.rb
module StoreFrontModule
  module Registries
    class StockTransferRegistriesController < ApplicationController
      def new
        @registry = StoreFrontModule::Registries::PurchaseOrderRegistry.new
      end
      def create
        @registry = StoreFrontModule::Registries::PurchaseOrderRegistry.new(registry_params)
        if @registry.valid?
          @registry.save
          @registry.parse_for_records
          redirect_to store_front_module_stock_transfer_registry_url(@registry), notice: "uploaded successfully"
        else
          render :new
        end
      end
      def show
        @registry = StoreFrontModule::Registries::PurchaseOrderRegistry.find(params[:id])
        @cart = current_cart
        @stock_transfer_order = StoreFrontModule::Orders::StockTransferOrderProcessing.new
      end
      private
      def registry_params
        params.require(:store_front_module_registries_purchase_order_registry).
        permit(:spreadsheet, :employee_id)
      end
    end
  end
end

app/views/store_front_module/registries/purchase_order_registries/new.html.erb
<div class="row">
  <div class="col-md-4 offset-md-4">
    <div class="card card-solid">
      <div class="card-header">
        <h3 class="subtitle-up"> Excel Upload Details </h3>
      </div>
      <div class="card-body">
        <span class="help-block"> Find excel file to upload. Please ensure file extension ends with '.xls' </span>
        <%= simple_form_for @registry, multipart: true, url: :store_front_module_purchase_order_registries do |f| %>
          <%= f.input :spreadsheet, label: false, as: :file %>
          <%= f.input :employee_id, input_html: { value: current_user.id }, as: :hidden %>
          <div class="card-footer">
            <%= f.submit "Upload Purchase", class: "btn btn-primary btn-block" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/store_front_module/registries/purchase_order_registries/show.html.erb
<%= @registry.purchase_order_line_items.count %>
<div class="row">
  <div class="col-md-8">
    <div class="card card-solid">
      <div class="card-header">
      </div>
      <div class="card-body">
        <div class="table table-responsive">
          <table class="table table-hover table-striped">
            <thead>
              <tr>
                <th><b>QTY</b></th>
                <th><b>DESCRIPTION</b></th>
                <th><span class="float-right"><b>UNIT COST</b></span></th>
                <th><span class="float-right"><b>TOTAL COST</b></span></th>
                <% StoreFront.all.order(:name).each do |store_front| %>
                  <th><%= store_front.name %> Selling Price</th>
               <% end %>



              </tr>
            </thead>
            <tbody>
              <% @purchase_order_line_items.each do |line_item| %>
                <tr>
                  <td><%= line_item.quantity %> <%= line_item.unit_code %></td>
                  <td width="300px"><%= line_item.name.try(:titleize) %><br>
                    <span class="text-muted"><%= line_item.bar_code %></span>
                  </td>
                  <td>
                    <span class="float-right">
                      <%= number_to_currency line_item.unit_cost %>
                    </span>
                  </td>
                  <td>
                    <span class="float-right"><%=number_to_currency line_item.total_cost %></span>
                  </td>
                  <% StoreFront.all.order(:name).each do |store_front| %>
                    <td><%= number_to_currency store_front.selling_prices.where(product: line_item.product).last.try(:price) %></td>
                  <% end %>

                  <td>
                  <%= link_to store_front_module_purchase_order_registry_purchase_order_line_item_path(id: line_item.id, purchase_order_registry_id: @registry.id), method: :delete do %>
                    <span class="fa fa-trash"></span>
                  <% end %>
                  </td>
                </tr>
              <% end %>
              <hr>
            </tbody>
          </table>
          <center><%= will_paginate @purchase_order_line_items %></center>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        <h3 class="subtitle-up"> Purchase Details </h3>
        <%= link_to store_front_module_purchase_order_registry_path(@registry), method: :delete do %>
          <span class="btn btn-sm btn-outline-danger" data-toggle="tooltip" title="Cancel Purchase"> <i class="fa fa-times"></i> Cancel Order </span>
        <% end %>
      </div>
      <div class="card-body">
        <center>
          <h4><%= number_to_currency @registry.purchase_order_line_items.sum(:total_cost) %></h4>
          <small>TOTAL</small>
        </center>
        <hr>
        <% if @registry.line_items.present? %>
          <%= simple_form_for @purchase_order, url: :store_front_module_purchase_order_processings do |f| %>
            <%= f.input :supplier_id, collection: Supplier.all.map{|a| [ a.name, a.id] }, input_html: { class: 'chosen-select' } %>
            <%= f.input :date, as: :string, input_html: { class: "datepicker" } %>
            <%= f.input :cart_id, input_html: { value: @cart.id }, as: :hidden %>
            <%= f.input :employee_id, input_html: { value: current_user.id }, as: :hidden %>
            <%= f.input :registry_id, input_html: { value: @registry.id }, as: :hidden %>
            <%= f.input :account_number, input_html: { value: SecureRandom.uuid }, as: :hidden %>
            <%= f.input :voucher_id, collection: Voucher.for_suppliers.unused.map{|a| [a.reference_number, a.id] }, input_html: { class: 'chosen-select' } %>
            <%=f.submit "Save Purchase", class: "btn btn-primary btn-block btn-lg", :accesskey => "C" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>