config/routes.rb
Rails.application.routes.draw do
  authenticate :user, -> (user) { user.proprietor? } do
  end
  unauthenticated :user do
    root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  end
  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: "users"}

  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'sales_clerk' if request.env['warden'].user }, as: :sales_department_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'proprietor' if request.env['warden'].user }, as: :prop_department_root
  root :to => 'products#index', :constraints => lambda { |request| request.env['warden'].user.role == 'stock_custodian' if request.env['warden'].user }, as: :stocks_department_root
  root :to => 'computer_repair_section/dashboard#index', :constraints => lambda { |request| request.env['warden'].user.role == 'technician' if request.env['warden'].user }, as: :technician_root
  resources :store, only: [:index]
	resources :customers do
    resources :departments, only: [:new, :create], module: :customers
    resources :refunds,         only: [:new, :create],                module: :customers
    resources :payments,        only: [:new, :create],                module: :customers
    resources :orders,          only: [:index, :edit, :update],                       module: :customers
    resources :repair_services, only: [:index],                       module: :customers
    resources :account,         only: [:index],                       module: :customers
    resources :other_credits,   only: [:index, :show, :new, :create], module: :customers
    resources :settings, only: [:index], module: :customers
  end
  resources :products do
    resources :unit_of_measurements, only: [:new, :create]
    match "/out_of_stock" => "products#out_of_stock",  via: [:get], on: :collection
    match "/low_on_stock" => "products#low_on_stock",  via: [:get], on: :collection

  	resources :stocks,          only: [:index, :new, :create, :edit, :update], module: :products
    resources :stock_transfers, only: [:index], module: :products
    resources :orders,          only: [:index], module: :products
    resources :settings,        only: [:index], module: :products
  end
  resources :line_items, only: [:new, :create, :edit, :update]
  resources :orders, only: [:index, :show, :new, :create, :destroy]
  resources :carts, only: [:destroy]
  resources :categories, only: [:new, :create]
  resources :reports, only: [:index]
  resources :customer_registrations, only: [:new, :create]
  resources :store_customer_registrations, only: [:new, :create]
  resources :work_order_customer_registrations, only: [:new, :create]


  namespace :reports do
    resources :purchase_returns, only: [:index]
    resources :store_fronts, only: [:show], module: :store_fronts do
      resources :inventories, only: [:index]
    end
    resources :work_orders, only: [:index]
    resources :released_work_orders, only: [:index]

    resources :sales, only: [:index]
    resources :cash_receipts, only: [:index]
    resources :repairs,       only: [:index]
    resources :products, only: [:index]
    resources :accounts_receivables, only: [:index]

  end
  resources :accounting, only: [:index]
  namespace :accounting do
    resources :entries, only: [:show]
    resources :fund_transfers, only: [:new, :create]
    resources :remittances, only: [:new, :create]
    resources :expenses, only: [:new, :create]
  end

  resources :settings, only: [:index]
  resources :businesses, only: [:edit, :update]

  resources :supplier_registrations, only: [:new, :create]
  namespace :suppliers do
    resources :merge_accounts, only: [:new, :create]
  end
  resources :suppliers, only: [:index, :show, :edit, :update] do
    resources :product_selections, only: [:new, :create], module: :suppliers
    resources :purchase_line_items, only: [:new, :create], module: :suppliers
    resources :purchase_orders, only: [:index], module: :suppliers
    resources :purchase_order_processings, only: [:create], module: :suppliers

    resources :account, only: [:index], module: :suppliers
    resources :voucher_amounts, only: [:new, :create, :destroy], module: :suppliers
    resources :vouchers, only: [:index, :create, :show], module: :suppliers
    resources :voucher_confirmations, only: [:create], module: :suppliers
    resources :payments, only: [:new, :create], module: :suppliers
  end
  resources :users, only: [:edit, :update]
  resources :registries, only: [:create, :show, :destroy]
  resources :employees, only: [:show, :edit, :update] do
    resources :repairs, only: [:index], module: :employees
    resources :remittances, only: [:new, :create], module: :employees
    resources :bank_remittances, only: [:new, :create], module: :employees
    resources :reports, only: [:index], module: :employees
    resources :sales, only: [:index], module: :employees
    resources :entries, only: [:index], module: :employees
    resources :cash_counts, only: [:new, :create], module: :employees
    resources :bill_counts, only: [:create], module: :employees
    resources :cash_on_hand_accounts, only: [:show], module: :employees do
    end
  end
  resources :cash_accounts, only: [:show] do

    resources :expenses, only: [:new, :create], module: :cash_accounts
    resources :cash_transfers, only: [:new, :create], module: :cash_accounts

  end
  resources :work_orders, only: [:index, :new, :create] do
    resources :payments, only: [:ew, :create], module: :work_orders
  end
  resources :work_order_statuses, only: [:edit, :update]
  namespace :computer_repair_section do
    resources :dashboard, only: [:index]
    resources :insights, only: [:index]


    resources :work_orders do
      resources :endorsements,    only: [:edit, :update], module: :work_orders
      resources :service_charges, only: [:new, :create, :destroy], module: :work_orders
      resources :additional_charges, only: [:new, :create], module: :work_orders
      resources :spare_parts, only: [:new, :create, :destroy]
      resources :service_claim_tags, only: [:show]
      resources :payments, module: :work_orders, only: [:new, :create]
      resources :refunds, module: :work_orders, only: [:new, :create]
      resources :charge_invoices, only: [:new, :create], module: :work_orders
    end
    resources :work_order_updates, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :knowledge_center, only: [:index]
  resources :product_units, shallow: true do
    resources :accessories, only: [:new, :create]
  end

  resources :sections, only: [:new, :create]
  resources :other_sales, only: [:new, :create]
  resources :entries, only: [:destroy]
  resources :capital_withdrawals, only: [:new, :create]
  resources :accessories, only: [:destroy]
  resources :search_results, only: [:index]
  resources :customer_account_mergings, only: [:new, :create], module: :settings
  resources :charge_invoices, only: [:index, :edit, :update]
  resources :cash_on_hand_accounts, only: [:new, :create], module: :accounting

  namespace :store_front_module do
    resources :stocks, only: [:show] do
      resources :sales, only: [:index], module: :stocks
      resources :internal_uses, only: [:index], module: :stocks
      resources :stock_transfers, only: [:index], module: :stocks
    end
    resources :sales_order_line_items, only: [:show, :edit, :update] do
      resources :cancellations, only: [:create], module: :sales_order_line_items
      resources :sales_returns, only: [:new, :create], module: :sales_order_line_items

    end
    resources :stock_transfer_order_line_items, only: [:show] do
      resources :cancellations, only: [:create], module: :stock_transfer_order_line_items
    end
    resources :purchase_order_line_items, only: [:show]

    resources :store_fronts, only: [:index, :show] do
      resources :sales_orders, only: [:index],               module: :store_fronts
      resources :accounts,    only: [:index, :new, :create], module: :store_fronts
      resources :reports,     only: [:index],                module: :store_fronts
      resources :inventories, only: [:index],                module: :store_fronts
      resources :work_orders, only: [:index],                module: :store_fronts
    end
    resources :stock_registry_processings, only: [:create]
    resources :stock_transfer_registries, only: [:new, :create, :show], module: :registries
    resources :received_stock_transfer_registries, only: [:new, :create, :show], module: :registries
    resources :purchase_order_registries, only: [:new, :create, :show, :destroy], module: :registries do
      resources :purchase_order_line_items, only: [:destroy]
    end
    resources :customers, only: [:show] do
      resources :credit_sales_order_line_item_processings, only: [:new, :create, :destroy]
      resources :cash_sales_order_line_item_processings, only: [:new, :create, :destroy]

      resources :credit_sales_order_processings, only: [:create], module: :order_processings
    end
    resources :credit_sales_orders, only: [:show] do
      resources :payments, only: [:new, :create], module: :credit_sales_orders
    end
    resources :line_items, only: [:show]
    resources :spoilages, only: [:index, :show], module: :orders
    resources :spoilage_order_line_item_processings, only: [:new, :create, :destroy], module: :line_items
    resources :spoilage_order_processings, only: [:create], module: :orders
    resources :purchase_order_line_item_registries, only: [:create]
    resources :unit_of_measurements, only: [:edit, :update], module: :settings
    resources :selling_prices, only: [:new, :create], module: :settings
    resources :stock_transfers, only: [:index, :show, :edit, :update, :destroy], module: :orders do

app/models/store_front_module/balance_finders/line_items.rb
module StoreFrontModule
  module BalanceFinders
    class LineItems
      attr_reader :line_items

      def initialize(args)
        @line_items = args.fetch(:line_items)
      end

      def compute
        line_items.
        total_converted_quantity
      end
    end
  end
end

app/controllers/branches/line_items_controller.rb
module Branches 
  class LineItemsController < ApplicationController
    def create 
      @branch = Branch.find(params[:branch_id])
      @cart = current_cart
      @line_item = @cart.line_items.create(line_item_params)
      @search = params[:search].to_s
      if @line_item.save 
        redirect_to new_branch_stock_transfer_url(@branch), notice: "added successfully"
      else 
        redirect_to new_branch_stock_transfer_url(@branch), alert: 'Quantity exceeded available stocks'
      end
    end 
    def destroy 
      @line_item = LineItem.find(params[:id])
      @line_item.destroy 
      redirect_to new_branch_stock_transfer_url(@branch), notice: 'removed successfully.'
    end
    def update 
      @line_item = LineItem.find(params[:id])
      @line_item.update(line_item_params)
      if @line_item.save 
        redirect_to new_order_path, notice: 'Markup added successfully'
      else 
        redirect_to new_order_path, alert: "Error"
      end 
    end

    private 
    def line_item_params
      params.require(:line_item).permit(:stock_id, :unit_cost, :total_cost, :quantity, :markup_amount, :search)
    end
  end
end

app/controllers/line_items/sales_returns_controller.rb
module LineItems
	class SalesReturnsController < ApplicationController
		def new 
			@line_item = LineItem.find(params[:line_item_id])
			if @line_item.returned?
				redirect_to order_path(@line_item.order), alert: "Item is already returned"
			else 
			  @sales_return = @line_item.build_sales_return
			end
			authorize :sales_return, :new?
		end
		def create
			@line_item = LineItem.find(params[:line_item_id])
			@sales_return = @line_item.create_sales_return(sales_return_params)
			@sales_return.barcode = @line_item.stock.barcode 
			@sales_return.name = @line_item.stock.name 
			authorize :sales_return, :create?
			if @sales_return.valid?
				@sales_return.save
				redirect_to order_path(@line_item.order), notice: "Item returned successfully."
			else 
				render :new 
			end 
		end

		private 
		def sales_return_params
			params.require(:sales_return).permit(:date, :sales_return_type, :remarks, :quantity)
		end
	end 
end 

app/controllers/line_items/stock_transfer_sales_returns_controller.rb
module LineItems
  class StockTransferSalesReturnsController < ApplicationController
    def new
      @line_item = LineItem.find(params[:line_item_id])
      if @line_item.returned?
        redirect_to stock_transfer_path(@line_item.stock_transfer), alert: "Item is already returned"
      else
        @sales_return = @line_item.build_sales_return
      end
      authorize :sales_return, :new?
    end
    def create
      @line_item = LineItem.find(params[:line_item_id])
      @sales_return = @line_item.create_sales_return(sales_return_params)
      @sales_return.barcode = @line_item.stock.barcode
      @sales_return.name = @line_item.stock.name
      authorize :sales_return, :create?
      if @sales_return.valid?
        @sales_return.save
        redirect_to stock_transfer_path(@line_item.stock_transfer), notice: "Item returned successfully."
      else
        render :new
      end
    end

    private
    def sales_return_params
      params.require(:sales_return).permit(:date, :sales_return_type, :remarks, :quantity)
    end
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
	def create 
		@cart = current_cart
		@line_item = @cart.line_items.create(line_item_params)
    @search = params[:search].to_s
		if @line_item.save 
		  redirect_to "/store?&search=#{params[:line_item][:search]}", notice: "added successfully"
		else 
			redirect_to store_index_url, alert: 'Quantity exceeded available stocks'
		end
	end 
	def destroy 
		@line_item = LineItem.find(params[:id])
		@line_item.destroy 
		redirect_to orders_url, notice: 'removed successfully.'
	end
  def update 
    @line_item = LineItem.find(params[:id])
    @line_item.update(line_item_params)
    if @line_item.save 
      redirect_to new_order_path, notice: 'Markup added successfully'
    else 
      redirect_to new_order_path, alert: "Error"
    end 
  end

	private 
	def line_item_params
		params.require(:line_item).permit(:stock_id, :unit_cost, :total_cost, :quantity, :markup_amount, :search)
	end
end

app/controllers/store_front_module/line_items/internal_use_order_line_item_processings_controller.rb
module StoreFrontModule
  module LineItems
    class InternalUseOrderLineItemProcessingsController < ApplicationController
      def new
        if params[:search].present?
          @pagy, @stocks   = pagy(current_store_front.stocks.processed.text_search(params[:search]))
          @pagy, @products = pagy(Product.text_search(params[:search]))
        end
        @cart = current_cart
        @internal_use_order_line_item = StoreFrontModule::LineItems::InternalUseOrderLineItemProcessing.new
        @internal_use_order = StoreFrontModule::Orders::InternalUseOrderProcessing.new
        @internal_use_order_line_items = @cart.internal_use_order_line_items.order(created_at: :desc)
      end
      def create
        @line_item = StoreFrontModule::LineItems::InternalUseOrderLineItemProcessing.new(line_item_params)
        if @line_item.valid?
          @line_item.process!
          redirect_to new_store_front_module_internal_use_order_line_item_processing_url, notice: "added to cart"
        else
          render :new
        end
      end
      def destroy
        @line_item = StoreFrontModule::LineItems::InternalUseOrderLineItem.find(params[:id])
        @line_item.destroy
        redirect_to new_store_front_module_internal_use_order_line_item_processing_url, notice: "Removed successfully"
      end

      private
      def line_item_params
        params.require(:store_front_module_line_items_internal_use_order_line_item_processing).
        permit(:quantity, :unit_of_measurement_id, :product_id, :unit_cost, :total_cost, :bar_code, :cart_id, :stock_id)
      end
    end
  end
end

app/controllers/store_front_module/line_items/purchase_order_line_item_processings_controller.rb
module StoreFrontModule
  module LineItems
    class PurchaseOrderLineItemProcessingsController < ApplicationController
      def new
        if params[:search].present?
          @products = Product.text_search_with_barcode(params[:search]).all
        end
        @cart = current_cart
        @purchase_order_line_item = StoreFrontModule::LineItems::PurchaseOrderLineItemProcessing.new
        @purchase_order = StoreFrontModule::Orders::PurchaseOrderProcessing.new
        @purchase_order_line_items = @cart.purchase_order_line_items.order(created_at: :desc)

      end
      def create
        @line_item = StoreFrontModule::LineItems::PurchaseOrderLineItemProcessing.new(line_item_params)
        if @line_item.valid?
          @line_item.process!
          redirect_to new_store_front_module_purchase_order_line_item_processing_url, notice: "added successfully"
        else
          render :new
        end
      end
      def destroy
        @line_item = StoreFrontModule::LineItems::PurchaseOrderLineItem.find(params[:id])
        @line_item.destroy
        redirect_to new_store_front_module_purchase_order_line_item_processing_url, notice: "Removed successfully"
      end

      private
      def line_item_params
        params.require(:store_front_module_line_items_purchase_order_line_item_processing).
        permit(:quantity, :unit_of_measurement_id, :product_id, :unit_cost, :total_cost, :bar_code, :cart_id)
      end
    end
  end
end

app/views/store_front_module/line_items/received_stock_transfer_order_line_item_processings/_searched_line_item_results.html.erb
<% @line_items.each do |line_item| %>

                   <%= simple_form_for @stock_transfer_order_line_item, url: :store_front_module_stock_transfer_order_line_item_processings do |f| %>
                      <div class="row">
                        <div class="col-md-2">
                          <p><b><%= line_item.name.try(:upcase) %></b></p>

                            <%= number_to_currency line_item.unit_of_measurement.price %>/<%= line_item.unit_code %><br>

                        </div>
                        <div class="col-md-2">
                          <%=line_item.available_quantity %> <%= line_item.unit_code %><br>
                          <small class="text-danger">AVAILABLE QTY</small>
                        </div>
                        <div class="col-md-3">
                        <%= f.input :quantity, as: :string, input_html: { oninput: 'calculateLineItemTotalCost()', id: 'line_item_quantity', value: 1}, autofocus: true %>
                      </div>
                      <div class="col-md-3">
                        <%= f.input :unit_of_measurement_id, input_html: { value: line_item.unit_of_measurement_id}, as: :hidden %>
                        <%= f.input :product_id, input_html: { value: line_item.product_id }, as: :hidden %>
                        <%= f.input :cart_id, input_html: { value: @cart.id }, as: :hidden %>
                        <%= f.input :bar_code, input_html: { value: params[:search] } %>
                        <%= f.input :purchase_order_line_item_id, input_html: { value: line_item.id } %>
                      </div>

                      <div class="col-md-2">
                        <br>
                        <% if line_item.available_quantity <= 0 %>
                          <span class="badge bg-red"> OUT OF STOCK </span>
                        <% else %>
                          <%= f.submit "Add", class: "btn btn-danger btn-sm" %>
                        <% end %>
                      </div>
                    </div>

                      <%= f.input :cart_id, input_html: { value: @cart.id }, as: :hidden %>




              <% end %>
<% end %>
<hr>

app/views/store_front_module/line_items/received_stock_transfer_order_line_item_processings/_searched_product_results.html.erb
<% @line_items.each do |line_item| %>

                   <%= simple_form_for @stock_transfer_order_line_item, url: :store_front_module_stock_transfer_order_line_item_processings do |f| %>
                      <div class="row">
                        <div class="col-md-2">
                          <p><b><%= line_item.name.try(:upcase) %></b></p>

                            <%= number_to_currency line_item.unit_of_measurement.price %>/<%= line_item.unit_code %><br>

                        </div>
                        <div class="col-md-2">
                          <%=line_item.available_quantity %> <%= line_item.unit_code %><br>
                          <small class="text-danger">AVAILABLE QTY</small>
                        </div>
                        <div class="col-md-3">
                        <%= f.input :quantity, as: :string, input_html: { oninput: 'calculateLineItemTotalCost()', id: 'line_item_quantity', value: 1}, autofocus: true %>
                      </div>
                      <div class="col-md-3">
                        <%= f.input :unit_of_measurement_id, input_html: { value: line_item.unit_of_measurement_id}, as: :hidden %>
                        <%= f.input :product_id, input_html: { value: line_item.product_id }, as: :hidden %>
                        <%= f.input :cart_id, input_html: { value: @cart.id }, as: :hidden %>
                        <%= f.input :bar_code, input_html: { value: params[:search] } %>
                        <%= f.input :purchase_order_line_item_id, input_html: { value: line_item.id } %>
                      </div>

                      <div class="col-md-2">
                        <br>
                        <% if line_item.available_quantity <= 0 %>
                          <span class="badge bg-red"> OUT OF STOCK </span>
                        <% else %>
                          <%= f.submit "Add", class: "btn btn-danger btn-sm" %>
                        <% end %>
                      </div>
                    </div>

                      <%= f.input :cart_id, input_html: { value: @cart.id }, as: :hidden %>




              <% end %>
<% end %>
<hr>

app/views/store_front_module/line_items/received_stock_transfer_order_line_item_processings/new.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="card card-success">
      <div class="card-header">
        <div class="row">
          <div class="col-md-6">
            <h3 class="subtitle-up"> Stock Transfers Section </h3><br>
            <span class="text-muted"> Generate stock transfers on this section </span>
          </div>
          <div class="col-md-6">
            <%= link_to 'Upload (EXCEL)', new_store_front_module_received_stock_transfer_registry_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
      <div class="card-body">
       <% if params[:search].present? %>
        <%=form_tag new_store_front_module_received_stock_transfer_order_line_item_processing_path, method: :get do %>
          <div class="input-group">
            <%= text_field_tag :search, params[:search], class: "form-control input-lg", placeholder: "Search Products..." %>
            <span class="input-group-btn">
              <%= button_tag(type: 'submit', id: "search-btn", class: "btn btn-success btn-lg") do %>
                <i class="fa fa-search"></i> Search
              <% end %>
            </span>
          </div>
        <% end %>
        <% else %>
         <%=form_tag new_store_front_module_received_stock_transfer_order_line_item_processing_path, method: :get do %>
          <div class="input-group">
            <%= text_field_tag :search, params[:search], autofocus: true,  class: "form-control input-lg", placeholder: "Search Products..."  %>
            <span class="input-group-btn">
              <%= button_tag(type: 'submit', id: "search-btn", class: "btn btn-success btn-lg") do %>
                <i class="fa fa-search"></i> Search
              <% end %>
            </span>
          </div>
        <% end %>
      <% end %>
        <br>
        <table class="table table-responsive">
          <tbody>
            <% if @products.present? %>
              <%= render 'store_front_module/line_items/received_stock_transfer_order_line_item_processings/searched_product_results' %>
            <% elsif @line_items.present? %>
              <%= render 'store_front_module/line_items/received_stock_transfer_order_line_item_processings/searched_line_item_results' %>
            <% end %>
          </tbody>
        </table>
        <hr>
        <% if @received_stock_transfer_order_line_items.present? %>
          <p class="text-muted"> ORDER DETAILS </p>
          <div class="table table-responsive">
            <table class="table table-hover table-striped">
              <thead>
                <tr>
                  <th><b>QTY</b></th>
                  <th><b>DESCRIPTION</b></th>
                  <th><span class="float-right"><b>UNIT COST</b></span></th>
                  <th><span class="float-right"><b>TOTAL COST</b></span></th>
                </tr>
              </thead>
              <tbody>
                <% @cart.received_stock_transfer_order_line_items.each do |line_item| %>
                  <tr>
                    <td><%= line_item.quantity %> <%= line_item.unit_code %></td>
                    <td width="300px"><%= line_item.name.try(:titleize) %> <span class="text-muted"><%= line_item.bar_code %></span>
                    </td>
                    <td>
                      <span class="float-right">
                        <%= number_to_currency line_item.unit_cost %>
                      </span>
                    </td>
                    <td>
                      <span class="float-right"><%=number_to_currency line_item.total_cost %></span>
                    </td>
                    <td>
                    <%= link_to store_front_module_stock_transfer_order_line_item_processing_path(line_item), method: :delete do %>
                      <span class="fa fa-trash"></span>
                    <% end %>
                    </td>
                  </tr>
                <% end %>
                <hr>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>
    </div>
  </div>
    <div class="col-md-4">
      <div class="card card-success">
        <div class="card-body">
<% if @cart.received_stock_transfer_order_line_items.present? %>
          <%= simple_form_for @received_stock_transfer_order, url: :store_front_module_received_stock_transfer_order_processings do |f| %>
            <%= f.input :destination_store_front_id, collection: StoreFront.all.map{|a| [ a.name, a.id] } %>
            <%= f.input :origin_store_front_id, input_html: { value: current_user.store_front_id }, as: :hidden %>
            <%= f.input :date, as: :string, input_html: { class: "datepicker" } %>
            <%= f.input :cart_id, input_html: { value: @cart.id }, as: :hidden %>
            <%= f.input :employee_id, input_html: { value: current_user.id }, as: :hidden %>
            <%= f.input :reference_number %>
        <%=f.submit "Save Stock Transfer", class: "btn btn-success btn-block btn-lg", :accesskey => "C" %>
        <% end %>
      <% end %>
      </div>

    </div>
  </div>