config/routes.rb
Rails.application.routes.draw do
  authenticate :user, -> (user) { user.proprietor? } do
  end
  unauthenticated :user do
    root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  end
  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: "users"}

  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'sales_clerk' if request.env['warden'].user }, as: :sales_department_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'proprietor' if request.env['warden'].user }, as: :prop_department_root
  root :to => 'products#index', :constraints => lambda { |request| request.env['warden'].user.role == 'stock_custodian' if request.env['warden'].user }, as: :stocks_department_root
  root :to => 'computer_repair_section/dashboard#index', :constraints => lambda { |request| request.env['warden'].user.role == 'technician' if request.env['warden'].user }, as: :technician_root
  resources :store, only: [:index]
	resources :customers do
    resources :departments, only: [:new, :create], module: :customers
    resources :refunds,         only: [:new, :create],                module: :customers
    resources :payments,        only: [:new, :create],                module: :customers
    resources :orders,          only: [:index, :edit, :update],                       module: :customers
    resources :repair_services, only: [:index],                       module: :customers
    resources :account,         only: [:index],                       module: :customers
    resources :other_credits,   only: [:index, :show, :new, :create], module: :customers
    resources :settings, only: [:index], module: :customers
  end
  resources :products do
    resources :unit_of_measurements, only: [:new, :create]
    match "/out_of_stock" => "products#out_of_stock",  via: [:get], on: :collection
    match "/low_on_stock" => "products#low_on_stock",  via: [:get], on: :collection

  	resources :stocks,          only: [:index, :new, :create, :edit, :update], module: :products
    resources :stock_transfers, only: [:index], module: :products
    resources :orders,          only: [:index], module: :products
    resources :settings,        only: [:index], module: :products
  end
  resources :line_items, only: [:new, :create, :edit, :update]
  resources :orders, only: [:index, :show, :new, :create, :destroy]
  resources :carts, only: [:destroy]
  resources :categories, only: [:new, :create]
  resources :reports, only: [:index]
  resources :customer_registrations, only: [:new, :create]
  resources :store_customer_registrations, only: [:new, :create]
  resources :work_order_customer_registrations, only: [:new, :create]


  namespace :reports do
    resources :purchase_returns, only: [:index]
    resources :store_fronts, only: [:show], module: :store_fronts do
      resources :inventories, only: [:index]
    end
    resources :work_orders, only: [:index]
    resources :released_work_orders, only: [:index]

    resources :sales, only: [:index]
    resources :cash_receipts, only: [:index]
    resources :repairs,       only: [:index]
    resources :products, only: [:index]
    resources :accounts_receivables, only: [:index]

  end
  resources :accounting, only: [:index]
  namespace :accounting do
    resources :entries, only: [:show]
    resources :fund_transfers, only: [:new, :create]
    resources :remittances, only: [:new, :create]
    resources :expenses, only: [:new, :create]
  end

  resources :settings, only: [:index]
  resources :businesses, only: [:edit, :update]

  resources :supplier_registrations, only: [:new, :create]
  namespace :suppliers do
    resources :merge_accounts, only: [:new, :create]
  end
  resources :suppliers, only: [:index, :show, :edit, :update] do
    resources :product_selections, only: [:new, :create], module: :suppliers
    resources :purchase_line_items, only: [:new, :create], module: :suppliers
    resources :purchase_orders, only: [:index], module: :suppliers
    resources :purchase_order_processings, only: [:create], module: :suppliers

    resources :account, only: [:index], module: :suppliers
    resources :voucher_amounts, only: [:new, :create, :destroy], module: :suppliers
    resources :vouchers, only: [:index, :create, :show], module: :suppliers
    resources :voucher_confirmations, only: [:create], module: :suppliers
    resources :payments, only: [:new, :create], module: :suppliers
  end
  resources :users, only: [:edit, :update]
  resources :registries, only: [:create, :show, :destroy]
  resources :employees, only: [:show, :edit, :update] do
    resources :repairs, only: [:index], module: :employees
    resources :remittances, only: [:new, :create], module: :employees
    resources :bank_remittances, only: [:new, :create], module: :employees
    resources :reports, only: [:index], module: :employees
    resources :sales, only: [:index], module: :employees
    resources :entries, only: [:index], module: :employees
    resources :cash_counts, only: [:new, :create], module: :employees
    resources :bill_counts, only: [:create], module: :employees
    resources :cash_on_hand_accounts, only: [:show], module: :employees do
    end
  end
  resources :cash_accounts, only: [:show] do

    resources :expenses, only: [:new, :create], module: :cash_accounts
    resources :cash_transfers, only: [:new, :create], module: :cash_accounts

  end
  resources :work_orders, only: [:index, :new, :create] do
    resources :payments, only: [:ew, :create], module: :work_orders
  end
  resources :work_order_statuses, only: [:edit, :update]
  namespace :computer_repair_section do
    resources :dashboard, only: [:index]
    resources :insights, only: [:index]


    resources :work_orders do
      resources :endorsements,    only: [:edit, :update], module: :work_orders
      resources :service_charges, only: [:new, :create, :destroy], module: :work_orders
      resources :additional_charges, only: [:new, :create], module: :work_orders
      resources :spare_parts, only: [:new, :create, :destroy]
      resources :service_claim_tags, only: [:show]
      resources :payments, module: :work_orders, only: [:new, :create]
      resources :refunds, module: :work_orders, only: [:new, :create]
      resources :charge_invoices, only: [:new, :create], module: :work_orders
    end
    resources :work_order_updates, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :knowledge_center, only: [:index]
  resources :product_units, shallow: true do
    resources :accessories, only: [:new, :create]
  end

  resources :sections, only: [:new, :create]
  resources :other_sales, only: [:new, :create]
  resources :entries, only: [:destroy]
  resources :capital_withdrawals, only: [:new, :create]
  resources :accessories, only: [:destroy]
  resources :search_results, only: [:index]
  resources :customer_account_mergings, only: [:new, :create], module: :settings
  resources :charge_invoices, only: [:index, :edit, :update]
  resources :cash_on_hand_accounts, only: [:new, :create], module: :accounting

  namespace :store_front_module do
    resources :stocks, only: [:show] do
      resources :sales, only: [:index], module: :stocks
      resources :internal_uses, only: [:index], module: :stocks
      resources :stock_transfers, only: [:index], module: :stocks
    end
    resources :sales_order_line_items, only: [:show, :edit, :update] do
      resources :cancellations, only: [:create], module: :sales_order_line_items
      resources :sales_returns, only: [:new, :create], module: :sales_order_line_items

    end
    resources :stock_transfer_order_line_items, only: [:show] do
      resources :cancellations, only: [:create], module: :stock_transfer_order_line_items
    end
    resources :purchase_order_line_items, only: [:show]

    resources :store_fronts, only: [:index, :show] do
      resources :sales_orders, only: [:index],               module: :store_fronts
      resources :accounts,    only: [:index, :new, :create], module: :store_fronts
      resources :reports,     only: [:index],                module: :store_fronts
      resources :inventories, only: [:index],                module: :store_fronts
      resources :work_orders, only: [:index],                module: :store_fronts
    end
    resources :stock_registry_processings, only: [:create]
    resources :stock_transfer_registries, only: [:new, :create, :show], module: :registries
    resources :received_stock_transfer_registries, only: [:new, :create, :show], module: :registries
    resources :purchase_order_registries, only: [:new, :create, :show, :destroy], module: :registries do
      resources :purchase_order_line_items, only: [:destroy]
    end
    resources :customers, only: [:show] do
      resources :credit_sales_order_line_item_processings, only: [:new, :create, :destroy]
      resources :cash_sales_order_line_item_processings, only: [:new, :create, :destroy]

      resources :credit_sales_order_processings, only: [:create], module: :order_processings
    end
    resources :credit_sales_orders, only: [:show] do
      resources :payments, only: [:new, :create], module: :credit_sales_orders
    end
    resources :line_items, only: [:show]
    resources :spoilages, only: [:index, :show], module: :orders
    resources :spoilage_order_line_item_processings, only: [:new, :create, :destroy], module: :line_items
    resources :spoilage_order_processings, only: [:create], module: :orders
    resources :purchase_order_line_item_registries, only: [:create]
    resources :unit_of_measurements, only: [:edit, :update], module: :settings
    resources :selling_prices, only: [:new, :create], module: :settings
    resources :stock_transfers, only: [:index, :show, :edit, :update, :destroy], module: :orders do

app/controllers/admin/employees/reports_controller.rb
module Admin
  module Employees
    class ReportsController < ApplicationController
      def index
        @employee  = User.find(params[:employee_id])
        @from_date = params[:from_date] ? Time.zone.parse(params[:from_date]) : Date.current.beginning_of_month
        @to_date = params[:to_date] ? Time.zone.parse(params[:to_date]) : Date.current.end_of_month

      end
    end
  end
end

app/controllers/employees/reports_controller.rb
module Employees
  class ReportsController < ApplicationController
    def index
      @employee = User.find(params[:employee_id])
    end
  end
end

app/controllers/reports/accounts_receivables_controller.rb
module Reports
  class AccountsReceivablesController < ApplicationController
    def index
      @customers = Customer.with_credits.sort
      respond_to do |format|
        format.pdf do
          pdf = Reports::AccountsReceivablesPdf.new(@customers, view_context)
          send_data pdf.render, type: 'application/pdf', disposition: 'inline', file_name: 'AR Report.pdf'
         pdf = nil
        end
      end
    end
  end
end

app/controllers/reports/cash_receipts_controller.rb
module Reports
  class CashReceiptsController < ApplicationController
    def index
      @from_date = Chronic.parse(params[:from_date].to_date)
      @to_date   = Chronic.parse(params[:to_date].to_date)
      @user      = User.find_by(id: params[:user_id])

      if @user.present?
        @cash_receipts = @user.cash_on_hand_account.debit_entries.entered_on(from_date: @from_date, to_date: @to_date)
      else
        @cash_receipts = AccountingModule::Account.cash_on_hand_accounts.entered_on(from_date: @from_date, to_date: @to_date)
      end

      respond_to do |format|
        format.pdf do
          pdf = Reports::CashReceiptsPdf.new(
            from_date:     @from_date,
            to_date:       @to_date,
            cash_receipts: @cash_receipts,
            employee:      @user,
            view_context:  view_context)
          send_data pdf.render, type: 'application/pdf', disposition: 'inline', file_name: 'Cash Receipts Report.pdf'
          pdf = nil
        end
      end
    end
  end
end

app/controllers/reports/products_controller.rb
module Reports
  class ProductsController < ApplicationController
    def index
      @categories = Category.all
      @products = Product.all
      respond_to do |format|
        format.xlsx
      end
    end
  end
end

app/controllers/reports/purchase_returns_controller.rb
module Reports
  class PurchaseReturnsController < ApplicationController
    def index
      @from_date = Chronic.parse(params[:from_date].to_date)
      @to_date = Chronic.parse(params[:to_date].to_date)
      @employee = User.find_by(id: params[:user_id])
      if @employee.present?
        @orders = @employee.sales_orders.ordered_on(from_date: @from_date, to_date: @to_date)
      else
			  @orders = StoreFrontModule::Orders::PurchaseReturnOrder.ordered_on(from_date: @from_date, to_date: @to_date)
      end
			respond_to do |format|
        format.xlsx
      end
    end
  end
end 

app/controllers/reports/released_work_orders_controller.rb
module Reports
  class ReleasedWorkOrdersController < ApplicationController
    def index
      @employee = User.find(params[:user_id])
      @from_date = params[:from_date] ? Time.zone.parse(params[:from_date]) : Date.current.beginning_of_month
      @to_date   = params[:to_date] ? Time.zone.parse(params[:to_date]) : Date.current.beginning_of_month

      @work_orders = @employee.work_orders.released_on(from_date: @from_date, to_date: @to_date)
      respond_to do |format|
        format.xlsx
      end
    end
  end
end

app/controllers/reports/repairs_controller.rb
module Reports
  class RepairsController < ApplicationController
    def index
      @from_date = params[:from_date] || DateTime.now.beginning_of_month
      @to_date = params[:to_date] || DateTime.now.end_of_month
      @employee = User.find(params[:user_id])
      @work_orders = @employee.work_orders.released.from(from_date: @from_date, to_date: @to_date)
      respond_to do |format|
        format.xlsx
      end
    end
  end
end

app/controllers/reports/store_fronts/inventories_controller.rb
module Reports
  module StoreFronts
    class InventoriesController < ApplicationController
      def index
      end
    end
  end
end

app/controllers/reports/work_orders_controller.rb
module Reports
  class WorkOrdersController < ApplicationController
    def index
      @work_orders = WorkOrder.all.to_a.sort_by(&:elapsed_time)
      respond_to do |format|
        format.xlsx
      end
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	def index
    @products = Product.all
	end
end

app/controllers/store_front_module/store_fronts/reports_controller.rb
module StoreFrontModule
  module StoreFronts
    class ReportsController < ApplicationController
      def index
        @store_front = current_business.store_fronts.find(params[:store_front_id])
      end
    end
  end
end 

app/views/reports/index.html.erb
  <div class="row">
    <div class="col-md-12">
      <div class="card card-default">
        <div class="card-header">
          <h3 class="subtitle-up"> Reports </h3>
          <p class="help-block"> Generate reports </p>
        </div>
        <div class="card-body">
          <h4 class="title"> Services </h4>
          <p class="category">Generate report for services</p><br>
          <%= form_tag({:action => "index", controller: "work_orders", format: 'pdf'}, {:method => :get})  do %>
            <div class="row">
              <div class="col-md-3">
                <div class="form-group">
                  <%= text_field_tag :from_date, @from_date, :class => 'datepicker form-control border-input', :placeholder => "From " %>
                </div>
              </div>
              <div class="col-md-3">
                <div clasps="form-group">
                  <%= text_field_tag :to_date, @to_date, :class => 'form-control border-input datepicker', :placeholder => "To " %>
                </div>
              </div>
              <div class="col-md-1">
                <button type="submit" class="btn btn-success"> Generate</button>
              </div>
            </div>
          <% end %>
          <hr>

          <h4 class="title"> Sales </h4>
          <p class="category">Generate report for sales</p><br>
          <%= form_tag({:action => "index", controller: "reports/sales", format: 'xlsx', user_id: current_user.id}, {:method => :get})  do %>
              <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                    <%= text_field_tag :from_date, @from_date, :class => 'datepicker form-control border-input', :placeholder => "From " %>
                  </div>
                </div>
                <div class="col-md-3">
                  <div clasps="form-group">
                    <%= text_field_tag :to_date, @to_date, :class => 'form-control border-input datepicker', :placeholder => "To " %>
                  </div>
                </div>
                <div class="col-md-3">
                  <div clasps="form-group">
                    <%= select_tag :store_front_id, options_for_select(current_business.store_fronts.map {|m| [m.name, m.id]}, params[:office_id]), class: ' form-control border-input', prompt: false %>
                  </div>
                </div>
                <div class="col-md-1">
                  <button type="submit" class="btn btn-success"> Generate</button>
                </div>
              </div>
            <% end %>
          <%=link_to reports_sales_path(user_id: nil, format: 'csv', from_date: Time.zone.now.beginning_of_day, to_date: Time.zone.now.end_of_day) do %>
	          <h4 class='subtitle-up'> Daily Sales </p>
	          <small>Generate report of sales for this day <%=Time.zone.now.strftime("%B %e, %Y") %></small>
	        <% end %>
          <hr>
          <h4 class="title-up"> Purchase Returns  </h4>
          <p class="category">Generate report for purchase returns</p><br>
          <%= form_tag({:action => "index", controller: "reports/purchase_returns", format: 'xlsx'}, {:method => :get})  do %>
              <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                    <%= text_field_tag :from_date, @from_date, :class => 'datepicker form-control border-input', :placeholder => "From " %>
                  </div>
                </div>
                <div class="col-md-3">
                  <div clasps="form-group">
                    <%= text_field_tag :to_date, @to_date, :class => 'form-control border-input datepicker', :placeholder => "To " %>
                  </div>
                </div>
                <div class="col-md-1">
                  <button type="submit" class="btn btn-success"> Generate</button>
                </div>
              </div>
            <% end %>
          <hr>
          <%=link_to reports_sales_path(user_id: nil, format: 'pdf', from_date: Time.zone.now.beginning_of_week, to_date: Time.zone.now.end_of_week) do %>
	          <p class="category"> Weekly Sales </p>
	          <small>Generate report of weekly sales </small>
	        <% end %>
          <hr>
          <%=link_to reports_sales_path(user_id: nil, format: 'pdf', from_date: Time.zone.now.beginning_of_month, to_date: Time.zone.now.end_of_month) do %>
             <p class="category"> Monthly Sales </p>
            <small>Generate report of sales for this month <%=Time.zone.now.strftime("%B %Y") %></small>
          <% end %>
          <hr>
          <%=link_to reports_sales_path(user_id: nil, format: 'pdf', from_date: Time.zone.now.beginning_of_year, to_date: Time.zone.now.end_of_year) do %>
	          <p class="category"> Yearly Sales </p>
	          <small>Generate report of sales for this year <%=Time.zone.now.year %></small>
	        <% end %>
          <hr>

          <h4 class="title"> Accounts Receivables </h4>
          <%=link_to reports_accounts_receivables_path(format: 'pdf') do %>
            <p class="category"> Generate Report </p>

          <% end %>
          <hr>
        </div>
      </div>
      <dic class='card'>
        <div class="card-body">
          <h4 class="title-up"> Inventories Report</h3>
          <% current_business.store_fronts.each do |store_front| %>
            <div class="row">
              <div class="col-md-6">
            <%= "#{store_front.name} Inventory" %>
          </div>
          <div class="col-md-6">
          <%= link_to 'Excel', store_front_module_store_front_inventories_path(store_front_id: store_front.id, format: 'csv'), class: 'btn btn-outline-primary' %>
        </div>
      </div>
            <hr>
          <% end %>