config/routes.rb
Rails.application.routes.draw do
  authenticate :user, -> (user) { user.proprietor? } do
  end
  unauthenticated :user do
    root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  end
  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: "users"}

  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'sales_clerk' if request.env['warden'].user }, as: :sales_department_root
  root :to => 'store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'proprietor' if request.env['warden'].user }, as: :prop_department_root
  root :to => 'products#index', :constraints => lambda { |request| request.env['warden'].user.role == 'stock_custodian' if request.env['warden'].user }, as: :stocks_department_root
  root :to => 'computer_repair_section/dashboard#index', :constraints => lambda { |request| request.env['warden'].user.role == 'technician' if request.env['warden'].user }, as: :technician_root
  resources :store, only: [:index]
	resources :customers do
    resources :departments, only: [:new, :create], module: :customers
    resources :refunds,         only: [:new, :create],                module: :customers
    resources :payments,        only: [:new, :create],                module: :customers
    resources :orders,          only: [:index, :edit, :update],                       module: :customers
    resources :repair_services, only: [:index],                       module: :customers
    resources :account,         only: [:index],                       module: :customers
    resources :other_credits,   only: [:index, :show, :new, :create], module: :customers
    resources :settings, only: [:index], module: :customers
  end
  resources :products do
    resources :unit_of_measurements, only: [:new, :create]
    match "/out_of_stock" => "products#out_of_stock",  via: [:get], on: :collection
    match "/low_on_stock" => "products#low_on_stock",  via: [:get], on: :collection

  	resources :stocks,          only: [:index, :new, :create, :edit, :update], module: :products
    resources :stock_transfers, only: [:index], module: :products
    resources :orders,          only: [:index], module: :products
    resources :settings,        only: [:index], module: :products
  end
  resources :line_items, only: [:new, :create, :edit, :update]
  resources :orders, only: [:index, :show, :new, :create, :destroy]
  resources :carts, only: [:destroy]
  resources :categories, only: [:new, :create]
  resources :reports, only: [:index]
  resources :customer_registrations, only: [:new, :create]
  resources :store_customer_registrations, only: [:new, :create]
  resources :work_order_customer_registrations, only: [:new, :create]


  namespace :reports do
    resources :purchase_returns, only: [:index]
    resources :store_fronts, only: [:show], module: :store_fronts do
      resources :inventories, only: [:index]
    end
    resources :work_orders, only: [:index]
    resources :released_work_orders, only: [:index]

    resources :sales, only: [:index]
    resources :cash_receipts, only: [:index]
    resources :repairs,       only: [:index]
    resources :products, only: [:index]
    resources :accounts_receivables, only: [:index]

  end
  resources :accounting, only: [:index]
  namespace :accounting do
    resources :entries, only: [:show]
    resources :fund_transfers, only: [:new, :create]
    resources :remittances, only: [:new, :create]
    resources :expenses, only: [:new, :create]
  end

  resources :settings, only: [:index]
  resources :businesses, only: [:edit, :update]

  resources :supplier_registrations, only: [:new, :create]
  namespace :suppliers do
    resources :merge_accounts, only: [:new, :create]
  end
  resources :suppliers, only: [:index, :show, :edit, :update] do
    resources :product_selections, only: [:new, :create], module: :suppliers
    resources :purchase_line_items, only: [:new, :create], module: :suppliers
    resources :purchase_orders, only: [:index], module: :suppliers
    resources :purchase_order_processings, only: [:create], module: :suppliers

    resources :account, only: [:index], module: :suppliers
    resources :voucher_amounts, only: [:new, :create, :destroy], module: :suppliers
    resources :vouchers, only: [:index, :create, :show], module: :suppliers
    resources :voucher_confirmations, only: [:create], module: :suppliers
    resources :payments, only: [:new, :create], module: :suppliers
  end
  resources :users, only: [:edit, :update]
  resources :registries, only: [:create, :show, :destroy]
  resources :employees, only: [:show, :edit, :update] do
    resources :repairs, only: [:index], module: :employees
    resources :remittances, only: [:new, :create], module: :employees
    resources :bank_remittances, only: [:new, :create], module: :employees
    resources :reports, only: [:index], module: :employees
    resources :sales, only: [:index], module: :employees
    resources :entries, only: [:index], module: :employees
    resources :cash_counts, only: [:new, :create], module: :employees
    resources :bill_counts, only: [:create], module: :employees
    resources :cash_on_hand_accounts, only: [:show], module: :employees do
    end
  end
  resources :cash_accounts, only: [:show] do

    resources :expenses, only: [:new, :create], module: :cash_accounts
    resources :cash_transfers, only: [:new, :create], module: :cash_accounts

  end
  resources :work_orders, only: [:index, :new, :create] do
    resources :payments, only: [:ew, :create], module: :work_orders
  end
  resources :work_order_statuses, only: [:edit, :update]
  namespace :computer_repair_section do
    resources :dashboard, only: [:index]
    resources :insights, only: [:index]


    resources :work_orders do
      resources :endorsements,    only: [:edit, :update], module: :work_orders
      resources :service_charges, only: [:new, :create, :destroy], module: :work_orders
      resources :additional_charges, only: [:new, :create], module: :work_orders
      resources :spare_parts, only: [:new, :create, :destroy]
      resources :service_claim_tags, only: [:show]
      resources :payments, module: :work_orders, only: [:new, :create]
      resources :refunds, module: :work_orders, only: [:new, :create]
      resources :charge_invoices, only: [:new, :create], module: :work_orders
    end
    resources :work_order_updates, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :knowledge_center, only: [:index]
  resources :product_units, shallow: true do
    resources :accessories, only: [:new, :create]
  end

  resources :sections, only: [:new, :create]
  resources :other_sales, only: [:new, :create]
  resources :entries, only: [:destroy]
  resources :capital_withdrawals, only: [:new, :create]
  resources :accessories, only: [:destroy]
  resources :search_results, only: [:index]
  resources :customer_account_mergings, only: [:new, :create], module: :settings
  resources :charge_invoices, only: [:index, :edit, :update]
  resources :cash_on_hand_accounts, only: [:new, :create], module: :accounting

  namespace :store_front_module do
    resources :stocks, only: [:show] do
      resources :sales, only: [:index], module: :stocks
      resources :internal_uses, only: [:index], module: :stocks
      resources :stock_transfers, only: [:index], module: :stocks
    end
    resources :sales_order_line_items, only: [:show, :edit, :update] do
      resources :cancellations, only: [:create], module: :sales_order_line_items
      resources :sales_returns, only: [:new, :create], module: :sales_order_line_items

    end
    resources :stock_transfer_order_line_items, only: [:show] do
      resources :cancellations, only: [:create], module: :stock_transfer_order_line_items
    end
    resources :purchase_order_line_items, only: [:show]

    resources :store_fronts, only: [:index, :show] do
      resources :sales_orders, only: [:index],               module: :store_fronts
      resources :accounts,    only: [:index, :new, :create], module: :store_fronts
      resources :reports,     only: [:index],                module: :store_fronts
      resources :inventories, only: [:index],                module: :store_fronts
      resources :work_orders, only: [:index],                module: :store_fronts
    end
    resources :stock_registry_processings, only: [:create]
    resources :stock_transfer_registries, only: [:new, :create, :show], module: :registries
    resources :received_stock_transfer_registries, only: [:new, :create, :show], module: :registries
    resources :purchase_order_registries, only: [:new, :create, :show, :destroy], module: :registries do
      resources :purchase_order_line_items, only: [:destroy]
    end
    resources :customers, only: [:show] do
      resources :credit_sales_order_line_item_processings, only: [:new, :create, :destroy]
      resources :cash_sales_order_line_item_processings, only: [:new, :create, :destroy]

      resources :credit_sales_order_processings, only: [:create], module: :order_processings
    end
    resources :credit_sales_orders, only: [:show] do
      resources :payments, only: [:new, :create], module: :credit_sales_orders
    end
    resources :line_items, only: [:show]
    resources :spoilages, only: [:index, :show], module: :orders
    resources :spoilage_order_line_item_processings, only: [:new, :create, :destroy], module: :line_items
    resources :spoilage_order_processings, only: [:create], module: :orders
    resources :purchase_order_line_item_registries, only: [:create]
    resources :unit_of_measurements, only: [:edit, :update], module: :settings
    resources :selling_prices, only: [:new, :create], module: :settings
    resources :stock_transfers, only: [:index, :show, :edit, :update, :destroy], module: :orders do

app/controllers/computer_repair_section/work_orders/payments_controller.rb
module ComputerRepairSection
  module WorkOrders
    class PaymentsController < ApplicationController
      def new
        @work_order = WorkOrder.find(params[:work_order_id])
        @entry = AccountingModule::WorkOrderPaymentProcessing.new
      end
      def create
        @work_order = WorkOrder.find(params[:work_order_id])
        @entry = AccountingModule::WorkOrderPaymentProcessing.new(entry_params)
        if @entry.valid?
          @entry.save
          redirect_to computer_repair_section_work_order_path(@work_order), notice: "Payment saved successfully."
        else
          render :new
        end
      end

      private
      def entry_params
        params.require(:accounting_module_work_order_payment_processing).permit(:user_id, :expense_amount, :work_order_id, :entry_date, :reference_number, :description, :amount, :expense_account_id)
      end
    end
  end
end

app/controllers/customers/payments_controller.rb
module Customers
  class PaymentsController < ApplicationController
    def new
      @customer = Customer.find(params[:customer_id])
      @entry = AccountingModule::CustomerPaymentForm.new
    end
    def create
      @customer = Customer.find(params[:customer_id])
      @entry = AccountingModule::CustomerPaymentForm.new(entry_params)
      if @entry.valid?
        @entry.save
        redirect_to @customer, notice: "Payment saved successfully."
      else
        render :new
      end
    end

    private
    def entry_params
      params.require(:accounting_module_customer_payment_form).permit(:user_id, :customer_id, :entry_date, :reference_number, :description, :amount, :tax_amount, :expense_account_id, :expense_amount)
    end
  end
end

app/controllers/store_front_module/credit_sales_orders/payments_controller.rb
module StoreFrontModule
  module CreditSalesOrders
    class PaymentsController < ApplicationController
      def new
        @order = StoreFrontModule::Orders::SalesOrder.find(params[:credit_sales_order_id])
        @payment = StoreFrontModule::Payments::CreditSalesOrderPaymentProcessing.new
      end
      def create
        @order = StoreFrontModule::Orders::SalesOrder.find(params[:credit_sales_order_id])
        @payment = StoreFrontModule::Payments::CreditSalesOrderPaymentProcessing.new(payment_params)
        if @payment.valid?
          @payment.process!
          redirect_to customer_url(@order.customer), notice: "Payment saved successfully."
        else
          render :new
        end
      end

      private
      def payment_params
        params.require(:store_front_module_payments_credit_sales_order_payment_processing).
        permit(:order_id, :employee_id, :date, :amount, :expense_amount, :expense_account_id, :reference_number, :description, :cash_on_hand_account_id)
      end
    end
  end
end

app/controllers/suppliers/payments_controller.rb
module Suppliers
  class PaymentsController < ApplicationController
    def new
     @supplier = Supplier.find(params[:supplier_id])
      @entry = AccountingModule::SupplierPaymentForm.new
    end
    def create
      @supplier = Supplier.find(params[:supplier_id])
      @entry = AccountingModule::SupplierPaymentForm.new(entry_params)
      if @entry.valid?
        @entry.save
        redirect_to @supplier, notice: "Payment saved successfully."
      else
        render :new
      end
    end

    private
    def entry_params
      params.require(:accounting_module_supplier_payment_form).permit(:user_id, :supplier_id, :entry_date, :reference_number, :description, :credit_account_id, :amount)
    end
  end
end

app/controllers/work_orders/payments_controller.rb
module WorkOrders
  class PaymentsController < ApplicationController
    def new
      @work_order = WorkOrder.find(params[:work_order_id])
      @payment = WorkOrders::PaymentProcessing.new
    end
    def create
      @work_order = WorkOrder.find(params[:work_order_id])
      @payment = WorkOrders::PaymentProcessing.new(payment_params)
      if @payment.valid?
        @payment.process!
        redirect_to computer_repair_section_work_order_url(@work_order), notice: "Payment processed successfully."
      else
        render :new
      end
    end

    private
    def payment_params
      params.require(:work_orders_payment_processing).permit(:recorder_id, :amount, :customer_id)
    end
  end
end

app/views/store_front_module/credit_sales_orders/payments/new.html.erb
<div class="row">
      <div class="col-md-7">
        <div class="card">

      <div class="card-body">
        <center>
          <%= image_tag(@order.commercial_document.avatar, class: "img-circle", height: 60, width: 60) %><br><br>
        <h3 class="subtitle-up"><%= @order.commercial_document.try(:name).try(:upcase) %></h3>
        </center>


         <span class="float-right"><%= link_to 'Print(PDF)', order_path(@order, format: 'pdf'), class: "btn btn-default btn-sm" %></span>
        <i class="icon-calendar"></i> <%= @order.date.strftime("%B %e, %Y") %><br>
              <% @order.line_items.each do |line_item| %>
                <div class="row">
                  <div class="col-md-2">
                    <%= line_item.quantity %> <%= line_item.unit_code %>
                  </div>
                  <div class="col-md-4">
                    <%=line_item.product_name %><br>
                    <small class="text-muted"><%= line_item.bar_code %></small>
                  </div>
                  <div class="col-md-2">
                    <span class="float-right"><%= number_to_currency line_item.total_cost %></span>
                  </div>
                  <div class="col-md-3">

                  </div>
                </div>
                <hr>
                <% end %>

          </div>
</div>
</div>

  <div class="col-md-5">
    <div class="card card-default">
      <div class="card-header with-border">
        <div class="row">
          <div class="col-md-6">
            <h4 class="title-up">TOTAL</h4>
          </div>
          <div class="col-md-6">
            <h4 class="title-up">
              <span class="float-right">
                <%= number_to_currency @order.total_cost %>
              </span>
            </h4>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-md-6">
            <h4 class="title-up">Balance</h4>
          </div>
          <div class="col-md-6">
            <h4 class="title-up">
              <span class="float-right">
                <%= number_to_currency @order.balance %>
              </span>
            </h4>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-10 offset-md-1">
            <%= simple_form_for [@order, @payment], url: :store_front_module_credit_sales_order_payments do |f| %>
              <%= f.error_notification %>
              <%= f.input :date , as: :string, input_html: { class: "datepicker" } %>
              <%= f.input :amount, as: :string %>

              <span class="help-block"> Input total amount of payment. </span>
              <%= f.input :expense_amount, label: "Discount/Tax", as: :string, input_html: { value: 0 }%>
              <%= f.input :expense_account_id, collection: current_business.accounts.expenses.map{ |a| [a.name, a.id] }, input_html: { class: 'chosen-select' } %>
              <%= f.input :order_id, input_html: { value: @order.id }, as: :hidden %>
              <%= f.input :employee_id, input_html: { value: current_user.id }, as: :hidden %>
              <%= f.input :reference_number, label: "Check No." %>
              <%= f.input :description, label: "Invoice # / PO #" %>
              <% if current_user.proprietor? %>
                <%= f.input :cash_on_hand_account_id, collection: User.cash_on_hand_accounts.map{|a| [a.name, a.id] }, selected: current_user.cash_on_hand_account_id, input_html: { class: 'chosen-select' } %>
              <% else %>
                <%= f.input :cash_on_hand_account_id, input_html: {value: current_user.cash_on_hand_account_id }, as: :hidden %>
              <% end %>

              <div class="card-footer">
                <%= f.submit "Save Payment", class: "btn btn-primary btn-block" %>
              </div>
              <br>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $("#store_front_module_payments_credit_sales_order_payment_processing_cash_on_hand_account_id").select2({
      theme: "bootstrap"
    });
     $("#store_front_module_payments_credit_sales_order_payment_processing_expense_account_id").select2({
      theme: "bootstrap"
    });
  });
</script>